### ISSUE TITLE
Exported images have no metadata

### ISSUE THREAD

**Issue by Thane5** [StudioPetrikas/Saulala#23]
I just noticed that my flickr uploads dont display the camera settings as usual. Apparently images exported from saulala have almost none of the original exif metadata.

**Comment by StudioPetrikas** [comment]
"No metadata" or "Almost no metadata"?

It should show the essential metadata provided by a smartphone, minus the location.

It's a bug if there's no metadata, but it'll be a feature request the specific metadata you are looking for is missing.

A lot of camera-native files are very different in a lot of ways.

An example would be very useful.

**Comment by Thane5** [comment]
Left: jpeg exported from Capture one opened in XNview. Right, jpeg from Saulala.
![image](https://github.com/user-attachments/assets/b6327b70-6c3f-44b0-882a-d55f69a8bfec)

I uploaded them here https://mega.nz/folder/luAkzJqD#IO8IQGJ93MGL46efWvrPOw

**Comment by StudioPetrikas** [comment]
Thanks for the file. 
It seems that it is a bug, for some reason Saulala is having trouble reading Fuji EXIF information. 

I will likely have to rewrite the whole EXIF 'module', since there are other issues with the current metadata implementation. It won't be ready for the next beta, but it's likely going to be the next thing on the list.

**Comment by StudioPetrikas** [comment]
Addressed in v0.8.9.8-beta.
